### ISSUE TITLE
Peer Review Comments 

### ISSUE THREAD

**Issue by Jratliffjr** [math241s24/project-02-prasiddhi#1]
---
name: Peer Review Comments 
about: Peer review of project proposal
title: Proposal peer review
labels: ''
assignees: "Jefferson Ratliff" 
---

The following is the peer review of the project proposal by [Prasiddhi Thapaliya  @[prasiddhi]. The team members that participated in this review are 

- [Jefferson Ratliff- @[jratliffjr]

- Describe the goal of the project.

The goal is to see how diffrent coffees from other countries vary by taste. 

- Describe the data used or collected.

The data being used was collected by a github user @jldbc called the Coffee Quality Institute which measures where coffee comes from as well as its flavor notes such as aroma, acidity, and sweetness. 

- Describe how the research question will be answered, e.g., what approaches/methods will be used.

The question will be answered using a wide-variety of diffrent visualization techniques as well as making a interactive maps and a Shinyapp 

- Is there anything that is unclear from the proposal?

I think finding a way to visualize both taste and geography is really interesting. I am just wondering how each value will be assessed/visualized. 

- Provide constructive feedback on how the team might be able to improve their project.

I think that having a strong plan for how you intend to visualize the data would be great. Have you thought about how you would account for the processing and roasting process as well as the level? Would that be an issue in making your work? 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation?

I am interested in seeing how geography changes the way coffee is experienced. I have never seen a map like that. 
I am also making a shiny app for my final so I am excited to see other projects that use similar methods.

- Provide constructive feedback on any issues with file and/or code organization.

Everyone looks very good and is clear as well as straightforward. 

- (Optional) Any further comments or feedback?

I am excited  by your idea and am excited to see your presentation!

**Comment by prasiddhith** [comment]
Thanks for the feedback! I decided not to include the roasting/processing/etc. in the shinyApp, so I hope the interactive map helped visualize the taste and geography
